# Generated by Django 4.1.6 on 2023-02-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_alter_menu_food_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu_list',
        ),
    ]
